import Link from "next/link";
import { Genre } from "../types/types";
import { Suspense } from "react";

type Props = {
  genre: Genre;
  id: number;
};
export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};
export const Badge = async (props: Props) => {
  const genre: Genre = props.genre;
  // console.log("props on badge", props);
  const res = await fetch(
    `https://api.themoviedb.org/3/discover/movie?with_genres=${props.genre.id.toString()}&language=en-US&page=1`
  );
  const data = await res.json();
  // console.log("filter genre", props.genre.id);
  return (
    <Suspense>
      <Link
        href={`/badge/${
          props.genre.name
        }/${props.genre.id.toString()}?language=en-US&page=1`}>
        <div
          key={genre.id}
          className="border bg-none border-gray-200 px-5 rounded-xl font-semibold text-foreground text-xs content-center justify-center">
          {genre.name}
        </div>
      </Link>
    </Suspense>
  );
};
